In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
test = [1,2,3]

In [ ]:
np.array(test)

array([1, 2, 3])

In [ ]:
arr = np.array(test)

In [ ]:
Test1 = [[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
Test1

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(Test1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.zeros(3) 

array([0., 0., 0.])

In [ ]:
np.ones(3) 

array([1., 1., 1.])

In [ ]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.linspace(0,3,9)

array([0.   , 0.375, 0.75 , 1.125, 1.5  , 1.875, 2.25 , 2.625, 3.   ])

In [ ]:
np.linspace(0,3,3)

array([0. , 1.5, 3. ])

In [ ]:
np.linspace(0,10,3,dtype=int)

array([ 0,  5, 10])

In [ ]:
np.linspace(0,3,9,dtype=int)

array([0, 0, 0, 1, 1, 1, 2, 2, 3])

In [ ]:
np.random.rand(3)

array([0.79997457, 0.34693203, 0.2702087 ])

In [ ]:
np.random.rand(3,3)

array([[0.20630524, 0.73181743, 0.71391684],
       [0.69702871, 0.90174137, 0.23281579],
       [0.55472662, 0.86310548, 0.71173984]])

In [ ]:
np.random.randint(1,50)

19

In [ ]:
np.random.randint(1,50,10)

array([23, 41,  5, 33, 22, 19, 34, 15, 48, 15])

In [ ]:
arr = np.arange(25)

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
ranint = np.random.randint(0,50,10)

In [ ]:
ranint


array([44, 19, 26, 35, 19, 32, 36, 41, 30, 27])

In [ ]:
ranint.max()

44

In [ ]:
ranint.min()

19

In [ ]:
ranint.argmin()

1

In [ ]:
ranint.argmax()

0

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr = arr.reshape(5,5)

In [ ]:
arr.shape

(5, 5)

In [ ]:
#Q.1 create a 1 d array of 11 item and find the index value data a[0] and a[0:4].
np.random.rand(11)

array([0.61977953, 0.76493978, 0.29259629, 0.01489026, 0.40496702,
       0.60658385, 0.5958703 , 0.94477738, 0.96371784, 0.83166404,
       0.53023265])

In [ ]:
ar=np.random.rand(11)

In [ ]:
ar

array([0.377264  , 0.23609958, 0.5256073 , 0.56824814, 0.10288797,
       0.13969042, 0.19176871, 0.29732131, 0.30108875, 0.0928227 ,
       0.91706261])

In [ ]:
print(ar[0])

0.3772639976143938


In [ ]:
print(arr[0:4])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [ ]:
Test1 = [[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
Test1

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
 Test1 [1][2]

6

In [ ]:
# Q.2 try to perform conditional operator like <,>  on the array .
arr[arr > 4] 

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [ ]:
arr[arr < 12] 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
my_array = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/datafile - Sheet1.csv',delimiter=",", skiprows=1)

In [ ]:
print (my_array)

   1  2  3  4   5   6   7
0  2  3  4  5   6   7   8
1  3  4  5  6   7   8   9
2  4  5  6  7   8   9  10
3  5  6  7  8   9  10  11
4  6  7  8  9  10  11  12


In [ ]:
np.savetxt("saved_numpy_data.csv", my_array, delimiter=",")